### ISSUE TITLE
Quickly get started with ialacol.

### ISSUE THREAD

**Issue by ranjanshivaji** [chenhunghan/ialacol#11]
<img width="1274" alt="Screenshot 2023-07-21 at 9 20 00 PM" src="https://github.com/chenhunghan/ialacol/assets/55846356/1e867879-8667-4977-b14e-67bb4ce6409a">

Hi So deployed the pod for openllama-7b, On a kind cluster. On a device that does not have any GPU. Will this model be able to run on a system with 16 GB ram. I have port forwarded the pod but with the curl not getting any responses. Any suggestions on what might be the issue? 

What all i did: 
helm repo add ialacol https://chenhunghan.github.io/ialacol
helm repo update
helm install openllama-7b ialacol/ialacol

kubectl port-forward svc/openllama-7b 8000:8000

curl -X POST \
     -H 'Content-Type: application/json' \
     -d '{ "messages": [{"role": "user", "content": "How are you?"}], "model": "open_llama_7b-q4_0-ggjt.bin"}' \
     http://localhost:8000/v1/chat/completions

**Comment by chenhunghan** [comment]
How many CPU cores did you give to kind cluster? Is it slow (or forever) to respond or there are some error codes.

**Comment by ranjanshivaji** [comment]
chenhunghan, Thanks for your response. Yes actually giving the kind cluster a bigger machine got this resolved.
