### ISSUE TITLE
Storage Class value named differently in PVC templates and documentation examples

### ISSUE THREAD

**Issue by ktaletsk** [chenhunghan/ialacol#25]
There is a mismatch between docs and templates that I noticed:

Templates expect `.Values.model.persistence.storageClassName`:
- https://github.com/chenhunghan/ialacol/blob/5cd87a8592244edde6657ca5b8df20f9d651b34d/charts/ialacol/templates/pvc-cache.yaml#L7-L9
- https://github.com/chenhunghan/ialacol/blob/5cd87a8592244edde6657ca5b8df20f9d651b34d/charts/ialacol/templates/pvc-model.yaml#L7-L9

But the example values all have `.Values.model.persistence.storageClass`, i.e.
https://github.com/chenhunghan/ialacol/blob/5cd87a8592244edde6657ca5b8df20f9d651b34d/examples/values/llama2-7b-chat.yaml#L14

As a result, inattentive users might not notice the difference and use not the intended storage class, but the default one

**Comment by chenhunghan** [comment]
Thanks, good catch 🙂
