### ISSUE TITLE
Downloading models fail with timeouts, retry is not enabled.

### ISSUE THREAD

**Issue by DavidARivkin** [chenhunghan/ialacol#58]
When downloading a number of models (clearly from Hugging Face), I get the following error every time, seemingly at exactly the same point as well for each respective model that I have tried, even very small ones.
ERROR: Error downloading model: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

I think the code needs to be modified to include retries.

It would also be helpful if the documentation described how we can download models manually from within the pod.

**Comment by chenhunghan** [comment]
Hello, you can add `DOWNLOAD_DEFAULT_MODEL: False` to skip the auto download, and manually download to `/app/models` in the pod, you are right about the documentation, will be update when I have time.

**Comment by DavidARivkin** [comment]
Since the pod does not have curl, wget, etc.  how do you suggest we manually download the file?

**Comment by 3deep5me** [comment]
Maybe an init container which downloads the models is a option.
