### ISSUE TITLE
accelerator for project

### ISSUE THREAD

**Issue by dyllamt** [chenhunghan/ialacol#6]
Hi @chenhunghan, very cool project. was looking for something like this when i saw that Falcon was out. Any recs on appropriate accelerators for using the 7B and 40B models? I'm going to try your project out, and I'm wondering if you've already experimented with appropriate node pool specifications for running the deployment.

happy to add some tf-templates in the repo for some different providers if you want to collaborate

**Comment by chenhunghan** [comment]
> Hi @chenhunghan, very cool project. was looking for something like this when i saw that Falcon was out. Any recs on appropriate accelerators for using the 7B and 40B models? I'm going to try your project out, and I'm wondering if you've already experimented with appropriate node pool specifications for running the deployment.
> 
> 
> 
> happy to add some tf-templates in the repo for some different providers if you want to collaborate

Sure! Welcome to fire a PR or just fork the repo. I am afraid there is no acceleration for falcon at the moment (just because ggml does support it... not yet afaik). Sorry for the late response, was on vacation :).

**Comment by chenhunghan** [comment]
Hello @dyllamt , the support for CUDA11/12 and METAL GPU acceleration has landed, check out the latest releases!
