### ISSUE TITLE
Unable to download HG model from specific branch in helm chart

### ISSUE THREAD

**Issue by thearchitectxy** [chenhunghan/ialacol#76]
Hi i am unable to set and download specific branch in the helm chart i get an invalid repo id  error when i append :BRANCH_NAME
for example this doesnt work TheBloke/zephyr-7B-alpha-GPTQ:gptq-4bit-32g-actorder_True

How do i get it work what should be value of  DEFAULT_MODEL_HG_REPO_ID and DEFAULT_MODEL_FILE

trying to use this 4bit 32g for best quality https://huggingface.co/TheBloke/zephyr-7B-alpha-GPTQ

Thanks @chenhunghan  @ktaletsk

**Comment by chenhunghan** [comment]
Download from branch is not supported yet, but should be easy to add.

**Comment by chenhunghan** [comment]
Sure, implementing it's trivial but I need to have access to GPU instances to test it e2e.

**Comment by thearchitectxy** [comment]
> Sure, implementing it's trivial but I need to have access to GPU instances to test it e2e.

Okay understood @chenhunghan  thanks for noting it down looking forward to seeing it. 
for now the solution is to download all data on the other branch and upload a new model on huggingface and upload the model files on main branch and use my personal repo

**Comment by chenhunghan** [comment]
fyi, branch merged, the env name is `GPTQ_MODEL_HG_REVISION`
